const ORDER_STATUS = {
    APPROVED: "APPROVED",
    NOT_APPROVED: "NOT_APPROVED",
    REQUESTED: "REQUESTED",
    RECEIVED: "RECEIVED",
    FULFILLED: "FULFILLED",
};

export default {
    ORDER_STATUS
}